### PR TITLE
Change to yaml.safe_load for python tests

### LINKED ISSUE #251: Repro testing failing due to python error
The repro build is failing because the python testing framework is using a deprecated API call to load `yaml` files.

https://accessdev.nci.org.au/jenkins/blue/organizations/jenkins/ACCESS-OM2%2Freproducibility/detail/reproducibility/126/pipeline/

Should be a simple fix.

### PR DESCRIPTION
**Pull request by aidanheerdegen**
Closes #251

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
@aekiss Fixing the python in the testing I thought it would be worthwhile adding simple linting testing, otherwise it is difficult to know if the python is even correct because it is almost impossible to run easily.

This has the benefit of adding some CI to the repo, which an be built on for other static testing that might be useful.

If you are happy with this I will squash and merge.

**Comment by aidanheerdegen** [comment]
Actually, just noticed the travis stuff is not current, and the PEP8 link is 4 years old. I'll fix that and incorporate that test into the GH CI

**Comment by aidanheerdegen** [comment]
@aekiss I don't want to merge this without someone else just saying "yeah sure". It's not doing much, but I don't want to force this on your arbitrarily.

**Comment by aidanheerdegen** [comment]
Should have mentioned, I have fired off a repro-PR to make sure the python test stuff didn't break

https://accessdev.nci.org.au/jenkins/blue/organizations/jenkins/ACCESS-OM2%2Freproducibility_pull_request/detail/reproducibility_pull_request/13/pipeline

**Comment by aekiss** [comment]
I'm happy to say "yeah sure" - it sounds sensible, and although I don't have much understanding of the details, I trust your judgement :-)

**Pull request merged**
